spring:
  profiles:
    active: db, core, wx
  messages:
    encoding: UTF-8

server:
  port: 98080
  
server.servlet.context-path=/corn/

logging:
  level:
    root:  ERROR
    org.springframework:  ERROR
    org.mybatis:  ERROR
    org.linlinjava.litemall.wx:  DEBUG
    org.linlinjava.litemall:  ERROR

swagger:
  production: false